# Generated by Django 6.0.3 on 2026-03-17 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_title', models.CharField(max_length=200, verbose_name='home title')),
                ('home_subtitle', models.CharField(max_length=200, verbose_name='home subtitle')),
                ('home_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_images', to='common.media')),
            ],
        ),
    ]
